#!/bin/bash -x
# Author: Denis Klimov <klimov.d.e@gmail.com>
set -e

MARLIN_GIT_DIR="$HOME/develop/tevo/Marlin"
GIT_SHA="2.1.2.1"

TEVO_CONFIG_DIR=`dirname $(realpath $0)`
MARLIN_ARDUINO_FILE="$MARLIN_GIT_DIR/Marlin/Marlin.ino"
LABEL="Build date: $(date '+%F %H:%m'). Branch: $GIT_SHA"

# Clone repo
if [ ! -d "$MARLIN_GIT_DIR" ]; then
    git clone https://github.com/MarlinFirmware/Marlin.git "$MARLIN_GIT_DIR"
fi

# Update repo
cd $MARLIN_GIT_DIR
git reset --hard HEAD
git pull
git branch -a |grep -q tevo-with-zver-config && git branch -d tevo-with-zver-config
git checkout -b tevo-with-zver-config "$GIT_SHA"


# Update config files in repo
cat $TEVO_CONFIG_DIR/Configuration.h      > "$MARLIN_GIT_DIR/Marlin/Configuration.h"
cat $TEVO_CONFIG_DIR/Configuration_adv.h  > "$MARLIN_GIT_DIR/Marlin/Configuration_adv.h"

sed -i -e "s/TEVO_BUILD_LABEL/$LABEL/" $MARLIN_GIT_DIR/Marlin/Configuration.h


echo "You can build Marlin with project Arduino IDE file $MARLIN_ARDUINO_FILE"
echo "Use 'Arduino/Genuino Mega or Mega 2560' board in Arduino IDE for compile and flash"
echo "Check that u8glib-HAL library was installed in Arduino IDE"
echo "You need to push reset button right before Arduino IDE starts to upload firmware after compile and checking it. The reset button was placed close to USB socket on the board. You can push it many times and stop push after you see starts uploading stage at Arduini IDE. Also you can use flash script from this dir. Push reset button and start flash script. Check that external power is ON.".
arduino $MARLIN_ARDUINO_FILE

