#!/bin/bash
ARDUINO_DIR="$HOME/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17"
$ARDUINO_DIR/bin/avrdude -C$ARDUINO_DIR/etc/avrdude.conf -patmega2560 -cusbasp -Pusb -Uflash:w:$HOME/.arduino15/packages/arduino/hardware/avr/1.8.4/bootloaders/stk500v2/stk500boot_v2_mega2560.hex:i -Ulock:w:0x0F:m
